site_name: Gen3 User Doc
site_url: https://uc-cdis.github.io/gen3-user-doc/
site_description: Gen3 Data Commons Documentation
site_author: University of Chicago, CDIS

repo_url: https://github.com/uc-cdis/gen3-user-doc/
edit_uri: ""

pages:
    - Home: index.md
    - User Guide:
        - Guide Overview: user-guide/guide-overview.md
        - Data Contribution: user-guide/data-contribution.md
        - Data Access: user-guide/data-access.md
        - Data Analysis: user-guide/data-anaylsis.md
    - Appendices:
        - Data Commons Architecture: appendices/architecture.md
        - Data Dictionary: appendices/data-dictionary.md
        - Working with the API: appendices/api-gen3.md
        - Working with the Proxy and Whitelist: appendices/proxy-whitelist.md
        - Managing Timepoints: appendices/timepoints.md
        - Template TSVs: appendices/template-tsvs.md
        #- Minimal Technical Data Elements: appendices/mtde.md (BPA specific)


theme: readthedocs


extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: ÔÉÅ
    - admonition
    - def_list

copyright: Copyright &copy; 2017 <a href="https://cdis.uchicago.edu">CDIS at UChicago</a>
google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
